steps:
  # build & push the container image
- name: "gcr.io/zipup-74430/createmodel-00002-roz"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/zipup-74430/createmodel"]
  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'createmodel', '--image', 'gcr.io/zipup-74430/createmodel', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
